name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Configure npm to ignore optional dependencies
      run: npm config set optional false

    - name: Install dependencies
      run: npm install --no-optional --legacy-peer-deps  # 安装依赖并跳过不可选依赖

    - name: Install TailwindCSS CLI
      run: npm install tailwindcss

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo_version: '0.145.0'

    - name: Build the site with Hugo
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
